# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AdjustDuplicatePoints
                                 A QGIS plugin
 adjust duplicate points
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-07
        copyright            : (C) 2019 by Ed B
        email                : boesiii@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AdjustDuplicatePoints class from file AdjustDuplicatePoints.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .adjust_duplicate_points import AdjustDuplicatePoints
    return AdjustDuplicatePoints(iface)
